### PR TITLE
Add another function

### PR DESCRIPTION
**Pull request by poojashresthacode**
Hy group 3.

I saw that you have used only the lambda function in the code, I think we have to use two functions as the requirement of the code. So I have added a map function to it and created a merge request. Please have a look at it once.

### CODE REVIEW

**Comment by laserlab** [comment]
Why was this closed?

**Comment by WildJimmy** [comment]
@laserlab I'm not totally sure. I missed this one, I think because it was closed before I checked the pull requests that day. I'll give it a look now

**Comment by WildJimmy** [comment]
So this looks like a fine change, but I looked through the closed pull requests and saw this one (https://github.com/ubsuny/23-Homework3G3/pull/38) that added the map function a little earlier that day. It also modified the original file instead of rewriting it into a jupyter notebook. It also looks like why this was closed was discussed in issue #45, with some confusion over the new file being a jupyter notebook, etc. 
That said, I'm going to merge this file because all it will do will add the jupyter notebook to the repository and I want to make sure they get credit on the homework for the commits since the changes would be reasonable and the work done looks good.

**Comment by laserlab** [comment]
They get credit in any case. No worries. Your comment is perfectly fine, in particular reference it the issue where it was discussed. Just add such a comment the next time to a pull request before you close it. I don’t want you guys to close pull requests in particular from external groups without comment.

**Comment by JustinJaniszewski** [comment]
I apologize. It says I closed it originally and I'm not sure if that was intentional.

**Pull request merged**
